on:
    push:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: test
          id: test
          uses: kenichiro-kimura/sample-github-container-action@0e409df16048b8f2cc95a430d1126c3d3ea3ebb3
          with:
            id_of_input: 'input value 1'
            id_of_input2: 'input value 2'
        - name: view result
          run: |
            echo ${{ env.id_of_output }}
            echo ${{ env.id_of_output2 }}
          env:
            id_of_output: ${{ steps.test.outputs.id_of_output }}
            id_of_output2: ${{ steps.test.outputs.id_of_output2 }}
